name: Pull Request

on:
  push:
    branches:
      - gabrielmarcelino165/*
      - fontegabriel/*
      - alvesoliveirasolucoes/*
      - rafaelmesquitamoura/*
      - tgetnerski/*
permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

  terraform:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./
        run: terraform init

      - name: Validate Terraform
        working-directory: ./
        run: terraform validate

      - name: Plan Terraform
        working-directory: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform plan

  create-pull-request:
    needs: [terraform, validate]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Dummy Change if No Changes
        run: |
          if git diff --quiet; then
            echo "No changes detected, making a dummy change."
            date > dummy.txt
            git add dummy.txt
            git commit -m "Dummy change to ensure PR creation"
          else
            echo "Changes detected, proceeding."
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Automated Pull Request"
          body: "This pull request was automatically created by GitHub Actions."
          labels: "automated-pr"
          branch: ${{ github.ref_name }}  # Branch from which the PR is created
          base: main  # Base branch for the PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
